### ISSUE TITLE
[Engine] Level warp during testing message issues.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/Moondust-Project#180]
![level_warp](https://cloud.githubusercontent.com/assets/7596025/20860417/c85b87ca-b988-11e6-9eec-c30935b70121.png)

- [ ] 1. Weird symbol, marked by ellipse.

- [ ] 2. Message is not formatted by config pack.

**Comment by Wohlstand** [comment]
1) that because "№" is result of TTF renderer. Usually that with characters which are not presented on the font maps. Seems I forgot to draw it for message box font (for menu font I drew many tables, for message font and others I still wasn't drew other tables, so, non presented characters are drew as TTF which is always wired)
2) Because it's a simple call of message box which usually spawns the engine default style (blue info, yellow warning, red error). I think, I can exapnd ability to configure message boxes of all types (usually can be configured generic style only (with no matter info/warn/error), but allow custom textures or font settings per every type of message box which also can be used from lua scripts and applied to all internal message boxes).

**Comment by Wohlstand** [comment]
The whole thing will be reworked during further reconstruction, so, closing this as abandoned.
